// Auto-generated by tools/figma-tokens/sd.build.mjs — DO NOT EDIT
// Run pnpm tokens:sync to regenerate

export const figmaColors = {
  colorTextPrimary: '#0a0a0a',
  colorTextSecondary: '#212121',
  colorTextDisabled: '#9e9e9e',
  colorTextInverse: '#ffffff',
  colorBgButton: '#ffffff',
  colorBgHover: '#f5f5f5',
  colorBgDisabled: '#e0e0e0',
  colorBgPage: '#f8f8f8',
  colorBorderDefault: '#b4b4b4',
  colorBorderFocus: '#666e82',
  colorBorderDisabled: '#d0d0d0',
  colorSemanticConfirm: '#1a73e8',
  colorSemanticCancel: '#d32f2f',
} as const

export const figmaColorsHighContrast = {
  colorTextPrimary: '#000000',
  colorTextSecondary: '#000000',
  colorTextDisabled: '#555555',
  colorTextInverse: '#ffffff',
  colorBgButton: '#ffffff',
  colorBgHover: '#ffff00',
  colorBgDisabled: '#cccccc',
  colorBgPage: '#ffffff',
  colorBorderDefault: '#000000',
  colorBorderFocus: '#000000',
  colorBorderDisabled: '#555555',
  colorSemanticConfirm: '#0000cc',
  colorSemanticCancel: '#cc0000',
} as const

export const figmaColorsLowPower = {
  colorTextPrimary: '#cccccc',
  colorTextSecondary: '#aaaaaa',
  colorTextDisabled: '#555555',
  colorTextInverse: '#000000',
  colorBgButton: '#1a1a1a',
  colorBgHover: '#2a2a2a',
  colorBgDisabled: '#111111',
  colorBgPage: '#000000',
  colorBorderDefault: '#444444',
  colorBorderFocus: '#888888',
  colorBorderDisabled: '#333333',
  colorSemanticConfirm: '#5588ff',
  colorSemanticCancel: '#ff6666',
} as const
