/**
 * sd.build.mjs
 * Style Dictionary build - transforms tokens.json into:
 *   - packages/components/src/tokens/tokens.css  (CSS custom properties)
 *   - packages/components/src/tokens/figma-colors.ts  (TypeScript exports)
 *
 * Usage: node sd.build.mjs
 */

import { readFileSync, existsSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TOKENS_PATH = resolve(__dirname, 'tokens.json')
const OUTPUT_DIR = resolve(__dirname, '../../packages/components/src/tokens')

if (!existsSync(TOKENS_PATH)) {
  console.error('❌ tokens.json not found. Run transform-tokens.ts first.')
  process.exit(1)
}

const tokens = JSON.parse(readFileSync(TOKENS_PATH, 'utf-8'))

/** Build CSS custom properties for a given mode */
function buildCssVars(modeTokens) {
  const prefix = '--kiosk-figma'
  const lines = []

  function walk(obj, path) {
    for (const [key, val] of Object.entries(obj)) {
      const newPath = [...path, key]
      if (val && typeof val === 'object' && 'value' in val) {
        const cssVar = `${prefix}-${newPath.join('-')}`
        lines.push(`  ${cssVar}: ${val.value};`)
      } else if (val && typeof val === 'object') {
        walk(val, newPath)
      }
    }
  }

  walk(modeTokens, [])
  return lines.join('\n')
}

const normalVars = buildCssVars(tokens.normal ?? {})
const hcVars = buildCssVars(tokens['high-contrast'] ?? {})
const lpVars = buildCssVars(tokens['low-power'] ?? {})
const globalVars = buildCssVars(tokens.global ?? {})

const css = `/* Auto-generated by tools/figma-tokens/sd.build.mjs — DO NOT EDIT */
/* Run pnpm tokens:sync to regenerate */

:root,
[data-kiosk-mode="normal"] {
${normalVars}
${globalVars}
}

[data-kiosk-mode="high-contrast"] {
${hcVars}
}

[data-kiosk-mode="low-power"] {
${lpVars}
}
`

const cssOutputPath = resolve(OUTPUT_DIR, 'figma-tokens.css')
writeFileSync(cssOutputPath, css, 'utf-8')
console.log(`✅ CSS tokens written to: packages/components/src/tokens/figma-tokens.css`)

/** Build TypeScript color exports */
function buildTsExports(modeTokens, prefix = 'kioskFigma') {
  const entries = []

  function walk(obj, path) {
    for (const [key, val] of Object.entries(obj)) {
      const newPath = [...path, key]
      if (val && typeof val === 'object' && 'value' in val && val.type === 'color') {
        const tsKey = newPath.map((s, i) =>
          i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)
        ).join('')
        entries.push(`  ${tsKey}: '${val.value}',`)
      } else if (val && typeof val === 'object' && !('value' in val)) {
        walk(val, newPath)
      }
    }
  }

  walk(modeTokens, [])
  return entries.join('\n')
}

const tsColors = `// Auto-generated by tools/figma-tokens/sd.build.mjs — DO NOT EDIT
// Run pnpm tokens:sync to regenerate

export const figmaColors = {
${buildTsExports(tokens.normal ?? {})}
} as const

export const figmaColorsHighContrast = {
${buildTsExports(tokens['high-contrast'] ?? {})}
} as const

export const figmaColorsLowPower = {
${buildTsExports(tokens['low-power'] ?? {})}
} as const
`

const tsOutputPath = resolve(OUTPUT_DIR, 'figma-colors.ts')
writeFileSync(tsOutputPath, tsColors, 'utf-8')
console.log(`✅ TS colors written to: packages/components/src/tokens/figma-colors.ts`)
console.log('🎉 Token sync complete!')
